#!/bin/sh
### BEGIN INIT INFO
# Provides:          app300
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Forever test app
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export RUNAS=mbareja

case "$1" in
start)
  sudo -H -u $RUNAS forever start /home/mbareja/projects/foreverjs-brownbag/app3000.json
  ;;
stop)
  sudo -H -u $RUNAS forever stop TheApp
  ;;
restart)
  $0 stop && sleep 1 && $0 start
  ;;
*)
  echo "Usage: /etc/init.d/app3000 {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
